version: '2'

volumes:
  data:

services:
  # dc run bash
  bash: &default
    build: .
    volumes: 
    - ./app:/app
    - data:/data
    command: bash

  # dc up server1
  server1:
    <<: *default
    command: ruby server1.rb
    ports: ["3000:3000"]
    links: [server2]
    environment: 
      PORT: 3000
      SERVER2_URL: http://server2:4000

  # dc up server2
  server2:
    <<: *default
    command: ruby server2.rb
    ports: ["4000:4000"]
    environment: 
      PORT: 4000

  test:
    <<: *default
    links: [server2]
    command: ruby test.rb
    environment: 
      SERVER2_URL: http://server2:4000

